# Manipulating NumPy Arrays

### *Copyright 2021-2022 Dr. George Papagiannakis,  papagian@csd.uoc.gr*
*All Rights Reserved*
### *University of Crete & Foundation for Research & Technology - Hellas (FORTH)*

This notebook is also based on parts of [Lectures on scientific computing with Python](http://github.com/jrjohansson/scientific-python-lectures) by [J.R. Johansson](http://jrjohansson.github.io). 

---

In [1]:
from numpy import *

## Indexing and slicing

### Indexing

We can index elements in an array using square brackets and indices:

In [2]:
v = array([1,2,3,4])

# v is a vector, and has only one dimension, taking one index
v[0]

1

In [3]:
M = random.rand(3,3)

# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

0.6881678581325174

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [4]:
M

array([[0.48162589, 0.90560013, 0.17022428],
       [0.43163024, 0.68816786, 0.37609162],
       [0.70814746, 0.23882793, 0.64894038]])

In [5]:
M[1]

array([0.43163024, 0.68816786, 0.37609162])

The same thing can be achieved with using `:` instead of an index: 

In [6]:
M[1,:] # row 1

array([0.43163024, 0.68816786, 0.37609162])

In [7]:
M[:,1] # column 1

array([0.90560013, 0.68816786, 0.23882793])

We can assign new values to elements in an array using indexing:

In [8]:
M[0,0] = 1

In [9]:
M

array([[1.        , 0.90560013, 0.17022428],
       [0.43163024, 0.68816786, 0.37609162],
       [0.70814746, 0.23882793, 0.64894038]])

In [10]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [11]:
M

array([[ 1.        ,  0.90560013, -1.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.70814746,  0.23882793, -1.        ]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [12]:
A = array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [13]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [14]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [15]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [16]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [17]:
A[:3] # first three elements

array([ 1, -2, -3])

In [18]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [19]:
A = array([1,2,3,4,5])

In [20]:
A[-1] # the last element in the array

5

In [21]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [22]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [23]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [24]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [25]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [26]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [27]:
B = array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [28]:
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [29]:
# same thing
row_mask = array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [30]:
x = arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [31]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [32]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [33]:
indices = where(mask)

indices

(array([11, 12, 13, 14]),)

In [34]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([5.5, 6. , 6.5, 7. ])

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [35]:
diag(A)

array([ 0, 11, 22, 33, 44])

In [36]:
diag(A, -1)

array([10, 21, 32, 43])

### take

The `take` function is similar to fancy indexing described above:

In [37]:
v2 = arange(-3,3)
v2

array([-3, -2, -1,  0,  1,  2])

In [38]:
row_indices = [1, 3, 5]
v2[row_indices] # fancy indexing

array([-2,  0,  2])

In [39]:
v2.take(row_indices)

array([-2,  0,  2])

But `take` also works on lists and other objects:

In [40]:
take([-3, -2, -1,  0,  1,  2], row_indices)

array([-2,  0,  2])

### choose

Constructs an array by picking elements from several arrays:

In [41]:
which = [1, 0, 1, 0]
choices = [[-2,-2,-2,-2], [5,5,5,5]]

choose(which, choices)

array([ 5, -2,  5, -2])

## Further reading

* Check out more introductory notebooks in **Juno**!
* [General questions about NumPy](https://www.scipy.org/scipylib/faq.html#id1)
* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial
* http://scipy.org/NumPy_for_Matlab_Users - A Numpy guide for MATLAB users.

## Versions

In [42]:
%reload_ext version_information

%version_information numpy

Software versions
Python 3.6.6+ 64bit [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
IPython 7.3.0
OS Darwin 18.5.0 x86_64 64bit
numpy 1.16.1
Thu Apr 25 16:15:16 2019 +03